const customRules10percentsFoilStandard = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 1,
    priceRangeFrom: 0,
    priceRangeTo: 0.5,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0.5,
    priceRangeTo: 20,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 20,
    priceRangeTo: 2000,
    priceRangeValueToSet: 0.5,
    behaviourId: 8,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  customRules10percentsFoilStandard,
};
