const customRules10percentsFoilStandard = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 20,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 20,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 8,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
const customRulesPlus10percentsFoilStandard = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 20,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 20,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
const customRules10percentsUPonMKMTrendsStandard = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 1,
    priceRangeFrom: 0,
    priceRangeTo: 0.5,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 0.5,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 1,
    priceRangeFrom: 0,
    priceRangeTo: 0.5,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 0.5,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const customRulesMinus5PercentOnKeywordsCards = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 0,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 7,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 1,
    priceRangeFrom: 0,
    priceRangeTo: 0.5,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 0.5,
    priceRangeTo: 200,
    priceRangeValueToSet: 0.5,
    behaviourId: 7,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
const customRulesMinus5PercentOnModernAbove30euros = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 30,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 30,
    priceRangeTo: 300,
    priceRangeValueToSet: 0.5,
    behaviourId: 7,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 30,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 30,
    priceRangeTo: 300,
    priceRangeValueToSet: 0.5,
    behaviourId: 7,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
const customRulesPlus5PercentOnModernAbove30euros = (scriptID) => [
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 30,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 30,
    priceRangeTo: 300,
    priceRangeValueToSet: 0.5,
    behaviourId: 1,
    mkmPriceGuideReference: 1,
    isForFoils: 0,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 3,
    priceRangeFrom: 0,
    priceRangeTo: 30,
    priceRangeValueToSet: 0.5,
    behaviourId: 2,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    ruleTypeId: 2,
    priceRangeFrom: 30,
    priceRangeTo: 300,
    priceRangeValueToSet: 0.5,
    behaviourId: 1,
    mkmPriceGuideReference: 1,
    isForFoils: 1,
    isForSigned: 0,
    isForPlaysets: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const create4RaritiesForScript = (scriptID) => [
  {
    idScript: scriptID,
    name: "mythic",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    name: "rare",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    name: "uncommon",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    idScript: scriptID,
    name: "common",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  customRules10percentsFoilStandard,
  customRulesPlus10percentsFoilStandard,
  customRules10percentsUPonMKMTrendsStandard,
  customRulesMinus5PercentOnKeywordsCards,
  customRulesMinus5PercentOnModernAbove30euros,
  customRulesPlus5PercentOnModernAbove30euros,
  create4RaritiesForScript,
};
